version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
updates:
  - package-ecosystem: 'docker'
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      exclude:
        - dependency-name: '@navikt/aap-behandlingsflyt-typescript-types'
        - dependency-name: '@navikt/aap-postmottak-backend-typescript-types'
        - dependency-name: '@navikt/aap-oppgave-typescript-types'
        - dependency-name: '@navikt/aap-statistikk-typescript-types'
        - dependency-name: '@navikt/aksel*'
        - dependency-name: '@navikt/ds*'
    open-pull-requests-limit: 10
    registries: '*'
    ignore:
      - dependency-name: '*'
        update-types: [ 'version-update:semver-major' ]
      - dependency-name: '@navikt/eslint-config-aap'
      - dependency-name: 'prettier'
      - dependency-name: '@typescript-eslint*'
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'
        versions: [ '9.x' ]
    groups:
      aap-backend-typescript-types:
        patterns:
          - '@navikt/aap-behandlingsflyt-typescript-types'
          - '@navikt/aap-postmottak-backend-typescript-types'
          - '@navikt/aap-oppgave-typescript-types'
          - '@navikt/aap-statistikk-typescript-types'
      aksel-dependencies:
        patterns:
          - '@navikt/aksel*'
          - '@navikt/ds*'
      react-dependencies:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      team-deps:
        patterns:
          - '@navikt/aap-felles*'
      testing:
        patterns:
          - 'vitest'
          - 'vitest-fetch-mock'
          - '@vitest/coverage-v8'
          - '@vitejs/plugin-react'
          - '@testing-library/react'
          - '@testing-library/user-event'
          - '@testing-library/dom'
          - '@testing-library/jest-dom'
          - 'jsdom'
      otel:
        patterns:
          - '@opentelemetry/api'
          - '@opentelemetry/api-logs'
          - '@opentelemetry/instrumentation'
          - '@opentelemetry/resources'
          - '@opentelemetry/sdk-logs'
          - '@opentelemetry/sdk-metrics'
          - '@opentelemetry/sdk-trace-base'
          - '@vercel/otel'
